### PR TITLE
Fixes Xcode 7 nullability check

### PR DESCRIPTION
**Pull request by OliverLetterer**

### CODE REVIEW

**Comment by andresbrun** [comment]
Thanks for the improvement @OliverLetterer! You are right, there is no point of using `cancelByProducingResumeData` just to pass nil.

**Comment by OliverLetterer** [comment]
I'm sorry to bother you any further, but would it be possible to get a minor CocoaPods release and version 0.2.1 including the last two fixes? 😊😊😊 (I always hate it when my project compiles with warnings)

**Comment by andresbrun** [comment]
Hi Oliver, thanks for your help. Version 0.2.1 is available now ;)

**Comment by OliverLetterer** [comment]
Wow this was fast. Thank you very much 😊✨🎉

**Pull request merged**
